### ISSUE TITLE
Traces of the issues in PMDK

### ISSUE THREAD

**Issue by zunchenhuang** [efeslab/hippocrates#5]
Hi hippocrates authors, I had multiples issues when installing the tool and wonder if there is a simple way to obtain the traces that hippocrates generates? Also, is it possible to get the issues related to PMDK as in Fig. 3 in source code? Thank you.

**Comment by iangneal** [comment]
Hi @zunchenhuang,

> I had multiples issues when installing the tool...

If you can provide me with some specifics, I can try to help you figure out what's wrong and fix the issues.

> ...wonder if there is a simple way to obtain the traces that hippocrates generates?

Hippocrates generates traces using [pmemcheck](https://github.com/pmem/valgrind), so you can just use pmemcheck to get the traces that Hippocrates would use.

> Also, is it possible to get the issues related to PMDK as in Fig. 3 in source code? 

These issues are from the PMDK issues repo (https://github.com/pmem/issues), so the link for any particular issue number is `https://github.com/pmem/issues/issues/{issue #}`. Here are all the links for convenience:

Row 1:

- https://github.com/pmem/issues/issues/452
- https://github.com/pmem/issues/issues/940
- https://github.com/pmem/issues/issues/943

Row 2:

- https://github.com/pmem/issues/issues/447
- https://github.com/pmem/issues/issues/458
- https://github.com/pmem/issues/issues/459
- https://github.com/pmem/issues/issues/460
- https://github.com/pmem/issues/issues/461
- https://github.com/pmem/issues/issues/585
- https://github.com/pmem/issues/issues/942
- https://github.com/pmem/issues/issues/945

**Comment by zunchenhuang** [comment]
@iangneal Thank you so much Ian! I tried to find the issues from your paper in pmdk's github issues but it turned out they became read-only.

Not sure why but ``dep\valgrind-pmem`` is empty...
Here is the message I got back when I run cmake under build:
```cmake ..
-- Linker detection: GNU ld
-- Found LLVM 8.0.1
-- Using LLVMConfig.cmake in: /usr/lib/llvm-8/cmake
-- Build type is set to RelWithDebInfo
-- Looking for clwb instruction - not found
-- Looking for clflushopt instruction - found
CMake Warning at cmake/functions.cmake:28 (message):
  000_SimplePerf tool set to NONE, not adding to validation script.
Call Stack (most recent call first):
  cmake/add_test_executable.cmake:43 (append_tool_lists)
  tests/perf/CMakeLists.txt:3 (add_test_executable)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
JemallocLib
    linked by target "example" in directory /home/pmem/efeslab-hippocrates-e4b1322/deps/RECIPE/P-CLHT
TbbLib
    linked by target "example" in directory /home/pmem/efeslab-hippocrates-e4b1322/deps/RECIPE/P-CLHT

-- Configuring incomplete, errors occurred!
See also "/home/pmem/efeslab-hippocrates-e4b1322/build/CMakeFiles/CMakeOutput.log".
See also "/home/pmem/efeslab-hippocrates-e4b1322/build/CMakeFiles/CMakeError.log".

```

**Comment by iangneal** [comment]
@zunchenhuang Sorry about this, the old pmemcheck repository no longer exists.

I updated the dependency in https://github.com/efeslab/hippocrates/commit/ccd15cb4c4ce95b4c3a393dbbcef7c21aa808a54.
