### ISSUE TITLE
Issues related to the tool installation

### ISSUE THREAD

**Issue by rodrig0antunes** [efeslab/hippocrates#6]
Hi Hippocrates authors, I had some issues while installing the tool and was wondering if any help could be provided. While following the provided compiling instructions I had the following error when running cmake under build. Thank you in advance.

```shell
-- Linker detection: GNU ld
-- Found LLVM 8.0.1
-- Using LLVMConfig.cmake in: /usr/lib/llvm-8/cmake
-- Build type is set to RelWithDebInfo
-- Looking for clwb instruction - not found
-- Looking for clflushopt instruction - found
CMake Warning at cmake/functions.cmake:28 (message):
  000_SimplePerf tool set to NONE, not adding to validation script.
Call Stack (most recent call first):
  cmake/add_test_executable.cmake:43 (append_tool_lists)
  tests/perf/CMakeLists.txt:3 (add_test_executable)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
JemallocLib
    linked by target "p-clht_test" in directory /home/rjba/Desktop/thesis/hippocrates/deps/RECIPE/P-CLHT
    linked by target "p-clht_example" in directory /home/rjba/Desktop/thesis/hippocrates/deps/RECIPE/P-CLHT
TbbLib
    linked by target "p-clht_test" in directory /home/rjba/Desktop/thesis/hippocrates/deps/RECIPE/P-CLHT
    linked by target "p-clht_example" in directory /home/rjba/Desktop/thesis/hippocrates/deps/RECIPE/P-CLHT

-- Configuring incomplete, errors occurred!
See also "/home/rjba/Desktop/thesis/hippocrates/build/CMakeFiles/CMakeOutput.log".
See also "/home/rjba/Desktop/thesis/hippocrates/build/CMakeFiles/CMakeError.log".
```

**Comment by iangneal** [comment]
Looks like we missed some dependencies. I believe you should be able to fix this error by installing `libtbb-dev libjemalloc-dev`, e.g.:

```sh
sudo apt install -y libtbb-dev libjemalloc-dev
```

Let me know if you have any other issues after this!

**Comment by rodrig0antunes** [comment]
Thank you for the help, it indeed solved that particular issue. However, another one has appeared regarding the compiling instruction `make PMINTRINSICS`. After building successfully the previous make instructions this one does not build delivering the following error.  Do not know if it's me doing something wrong here, but I made sure that PMEMCHECK was built before PMINTRINSICS. Thank you again in advance.

```
Building C object src/intrinsic/CMakeFiles/PMINTRINSICS.dir/persistent_intrinsics.c.o
/home/rjba/Desktop/thesis/hippocrates/src/intrinsic/persistent_intrinsics.c:168:9: error: always_inline function '_mm_clwb' requires target feature 'clwb', but would be inlined into
      function 'PMFIXER_memset_dumb' that is compiled without support for 'clwb'
        _mm_clwb(&d[i]);
        ^
1 error generated.
ERROR:Failed to compile using given arguments: [-DPMINTRINSICS_EXPORTS -I/usr/lib/llvm-8/include -I/home/rjba/Desktop/thesis/hippocrates/src/common -I/home/rjba/Desktop/thesis/hippocrates/build/deps/valgrind-pmem/include -O2 -g -fPIC -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O0 -march=native -o CMakeFiles/PMINTRINSICS.dir/persistent_intrinsics.c.o -c /home/rjba/Desktop/thesis/hippocrates/src/intrinsic/persistent_intrinsics.c]
make[3]: *** [src/intrinsic/CMakeFiles/PMINTRINSICS.dir/build.make:63: src/intrinsic/CMakeFiles/PMINTRINSICS.dir/persistent_intrinsics.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:2139: src/intrinsic/CMakeFiles/PMINTRINSICS.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2146: src/intrinsic/CMakeFiles/PMINTRINSICS.dir/rule] Error 2
make: *** [Makefile:802: PMINTRINSICS] Error 2
```

**Comment by iangneal** [comment]
Ah, it seems that your CPU doesn't support the `clwb` instruction (you can check this with `lscpu | grep clwb`). However, it was easy for me to reproduce and patch this issue on my end, so if you switch to the `main` branch and update to https://github.com/efeslab/hippocrates/commit/65c68e804cdafff59d6c0fa1554fb9295694f5a4, you should be able to build `PMINTRINSICS` now. 

If you still have trouble with this, please attach the output of `lscpu`. If you have issues with something else, let me know and I'll see what I can do!

**Comment by iangneal** [comment]
I'll mark this as closed with the inclusion of https://github.com/efeslab/hippocrates/commit/65c68e804cdafff59d6c0fa1554fb9295694f5a4 and https://github.com/efeslab/hippocrates/commit/55f32c1df31382ad0a96eef2225b0ed3af0a9abe. If you have any other issues, feel free to open another issue!

**Comment by nextdimen** [comment]
@rodrig0antunes Were you able to run ./verify after your installation?
